### ISSUE TITLE
Grid headers can not be aligned

### ISSUE THREAD

**Issue by BrandonBV** [Servoy/aggridcomponents#10]
I have tried to align the AG Grid headers with the content that is in the grid columns but I have not been able to. I can however align the column data easily by setting a css style class to the the column. When I apply a similar css styling to the header style class it does not align and it seems that this is because the label is contained in ag-cell-label while the header style class is altering ag-header-cell. Is there any way to align the column headers to match the column data?

**Comment by paronne** [comment]
Hi, the alignment on the header doesn't work directly for you because the header has a more complex structure compared to the cell. Particoularly the div containing the header text (.ad-header-cell-text) doesn't take the full header width, therefore the aligment has no effect.
You can try something like the sample below in your css.

```
.cell-right {
text-align:left;
}

.cell-right .ag-header-cell-text {
    width: 100%;
}
```

**Comment by BrandonBV** [comment]
Hi Paolo, 

Thank you for the help, that fixed the issue.
