### ISSUE TITLE
Using headerCheckbox to select records

### ISSUE THREAD

**Issue by wvitpr** [Servoy/aggridcomponents#109]
How are we to use headerCheckbox? is there a onAction event somewhere?

**Comment by gboros** [comment]
when you set is for a column, it will show a checkbox in the header, and onSelectedRowsChanged will be called whenever it is clicked, with: isgroupselection= true (it is a group selection), groupcolumnid = id_of_column, groupkey = null (because this handler is also used for selection groups, in which case it is the group name), groupselection = true/false based on the check state; you need to actually select the rows in the model when this handler is called;
