### ISSUE TITLE
Get Column Name / Header Text

### ISSUE THREAD

**Issue by ErosN** [Servoy/aggridcomponents#3]
Can we add the ability to get the Column Name or Header Text similar to how you can get it from the servoyextra-table ( table_1.columns[columnindex].headerText ).

AG-Grid already seems to have functions that get you that information in the Column API: https://www.ag-grid.com/javascript-grid-column-api/#gsc.tab=0

**Comment by ErosN** [comment]
Hi Paolo,

The getJSONProperty is returning an error:

```
ERROR com.servoy.j2db.util.Debug - TypeError: Cannot call method "getJSONProperty" of  (C:\Projects\DevWorkspace\WebClient\forms\dm_contracts_details.js#208) (Form Context: dm_contracts_details), JSEvent(type = onCellClick, source = Component: <groupingtable_1>, formName = dm_contracts_details, elementName = groupingtable_1, timestamp = 2017-11-01 12:00:38.679,modifiers = 0,x =1436,y = 271,data = null)
	at C:\Projects\DevWorkspace\WebClient\forms\dm_contracts_details.js:208 (onCellClickGrid)
```

**Comment by paronne** [comment]
Hi, i believe your problem is here

**Comment by paronne** [comment]
Hi, can you show me your onCellClicked method ?
The agTable seems to be undefined in your case; that would be the case if you are getting the wrong JSForm with the solutioModel.getForm() or if the element's name is wrong.
Can you confirm that the form name is correct and the element's name is also correct ?

**Comment by ErosN** [comment]
It looks like its getting the correct form, and the right element.

Thanks,
Eros

![image](https://user-images.githubusercontent.com/32494592/32285119-b486e1b8-beff-11e7-82c3-53358dae675c.png)

**Comment by paronne** [comment]
I see your problem. Since you are in a responsive form the usage of solutionModel is slightly different. Elements are not directly referenced from the JSForm but from the hierarchy of JSLayoutContainers of your form (jsForm.getLayoutContainers()[idx].getLayoutContainers[idx2]...getWebComponent(name)). The containers of your form, such as row, columns, etc are the JSLayoutContainers of your form in solutionModel; 
you can use the method jsForm.findWebComponent("groupingtable_1"); which returns the component with the given name through the whole form hierarchy of JSlayoutContainers.
