### ISSUE TITLE
Empty column values now showing null

### ISSUE THREAD

**Issue by wvitpr** [Servoy/aggridcomponents#42]
Please see screenshot

![image](https://user-images.githubusercontent.com/83966/71219378-00a21c00-2319-11ea-95bf-86bc835a7e7c.png)

**Comment by wvitpr** [comment]
Any news on this issue?

**Comment by wvitpr** [comment]
HI Gabi,

Thankyou for the fix, When will it be available for download. I am doing a
customer demo early next week.. Happy new year btw 😊



*From:* Gabi <notifications@github.com>
*Sent:* Monday, 6 January 2020 10:11 PM
*To:* Servoy/aggridcomponents <aggridcomponents@noreply.github.com>
*Cc:* wvitpr <proutley@wvit.com.au>; Author <author@noreply.github.com>
*Subject:* Re: [Servoy/aggridcomponents] Empty column values now showing
null (#42)



Closed #42 <https://github.com/Servoy/aggridcomponents/issues/42> via
afcd3f8
<https://github.com/Servoy/aggridcomponents/commit/afcd3f895c1a6b2a9ac4714d4c8ed8d0d167b810>
.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Servoy/aggridcomponents/issues/42?email_source=notifications&email_token=AAAUP7VAR62TFUU7NF4KWK3Q4MGUDA5CNFSM4J5TN7A2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOVZDMVBA#event-2923874948>,
or unsubscribe

**Comment by seanthomasdevlin** [comment]
Hi wvitpr,

It may be a little time before we make a new binary release, but you can always test the latest by running from source, either by pulling from git or downloading the zip.

Are you familiar with how to do that ?

Best,
Sean

**Comment by wvitpr** [comment]
Hi Sean,
Oh ok, I'm happy to download, but not sure what to do with it. What folder
does it go into?

**Comment by seanthomasdevlin** [comment]
Hi wvitpr,

I missed your last message while traveling and didn't see it because the issue is marked closed. Sorry for that. To run (any) package from source, 

- click green download button > download as zip. 
- Extract the package folder "aggrid". 
- From eclipse, file >import >general > projects into workspace and select your "aggrid" folder. Then you should see it in the solution explorer. 
- Right-click Servoy Packages > Add Servoy Package Project Reference and select the project
