### ISSUE TITLE
Grid Height in Responsive Form in a tabPanel doesn`t work

### ISSUE THREAD

**Issue by juanetec** [Servoy/aggridcomponents#48]
Hi,
reading your wiki for Grid Height in Responsive y follow it and it works perfect.

> Adding a table in a flex-content layout and setting the table responsiveHeight property to 0, let the table grow up to 100% height of parent element (see more on flex-layout here).

![Image 2](https://user-images.githubusercontent.com/26114868/80912888-1e0bdb80-8d38-11ea-96da-77c4ccd2a10e.png)

But if that form I try to show in an another responsive form through a tabPannel (Bootstrap Components) it does not show the related form.

![Image 4](https://user-images.githubusercontent.com/26114868/80913138-3aa91300-8d3a-11ea-9c3a-0618ce808907.png)

What I am doing wrong?
What the proper way to solve that situation?

Thanks in advance

Un Saludo 

Juan Ramírez

**Comment by jcompagner** [comment]
what does it look like in the browser if you inspect the element?
the tabpanel is 500 big? but the form inside that how big is that? (that holds the grid)

**Comment by juanetec** [comment]
Hi, 
there is a servoy solution example that I try to explain what I try to do.
In brief, what I try to do is in a responsive form, which has the component tabPanel (could be auto resize in e responsive form?) and in this tabpannel I want to show a form with an Ag-grid. This Ag-grid have to be auto resize.


[gridResponsive.zip](https://github.com/Servoy/aggridcomponents/files/4579411/gridResponsive.zip)

Un Saludo

Juan Ramírez

**Comment by gboros** [comment]
The problem seems to be with the tabpanel that doesn't force 100% to it's innerform. Playing a bit with css, if you set the tabpanel's "containerStyleClass" to 
.tab-display{
	display: grid;
}
that the grid will fill vertically (having responsiveHeight = 0), but the tab container will have a scroll because of that row with the text at top - not sure how you could avoid that, if you really need to show also other rows, beside the flex container with the grid

**Comment by paronne** [comment]
Hi Juan,

Using responsiveHeight 0 on the grid will let the grid use 100% of the parent container. Therefore the parent container (the form) should have a known height, which is either fixed px or inheriting 100% of it's parent container. Note, the row on top of your form will "break" the layout. You should place the row inside the flex-header.

The problem is indeed within the TabPanel; the tab panel and all it's sub-div should have a known height. The tabpanel has inner tabs which do not use 100% of the available height. 

When a botstrap tabpanel contains a responsive form, will set a min-height = 500px ( that's the tabpanel height property) to the form and will let overflow it if needed. Having a min-height the layuot of the inner form won't be able to fill 100% of it (https://stackoverflow.com/questions/8468066/child-inside-parent-with-min-height-100-not-inheriting-height) 

Your option is to set a fixed height to the form itself via styleclass (e.g height:500px) or set a known height to the tabpanel (e.g. height-500px) and use similar CSS to let the inner tabs fill the height till 100%.

```
/* calculate tabpanel header size and fill height, take into account the tabs height */
.bts-tabpanel.full-height>.tab-content {
    height: calc(100% - 43px);
}

.bts-tabpanel.full-height>.tab-content>.tab-pane,
.bts-tabpanel.full-height>.tab-content>.tab-pane>div {
    height: 100%;
    overflow: auto;
}

.height-500 {
	height: 500px;
}
```

**Comment by juanetec** [comment]
Thanks Paolo, 
I solved it following your indication.
