### ISSUE TITLE
onCellDoubleClick argument JSRecord is not a JSRecord is an object

### ISSUE THREAD

**Issue by juanetec** [Servoy/aggridcomponents#50]
Hi,
the process onCellDoubleClick have 4 arguments  the third argument says that is a JSRecord but is not , is an object. the problem is when we are using de svyNavigation in the process "scopes.svyNavigation.open" we are doing tricks things to change to a JSRecord . 
I was wondering if the right way, shouldn't it be to return a JSRecord?

Un Saludo

Juan Ramírez

**Comment by gboros** [comment]
Hi,
it is an object, because for grouped records, the clicked record does not actually have a matching foundset in Servoy code, and so it can't return a record; for non-grouped records, it does return the right JSRecord, as those are from the component's foundset. There is already a case open for this on Servoy support, https://support.servoy.com/browse/SVY-14981, the fix maybe will be only a rename of the argument, from record to row, and a better documentation.

Regards,
Gabi

**Comment by gboros** [comment]
Hi,
after having another look I did see that we actually can use the record type for the callbacks, and that will be always a record in the the grid's foundset, even if the callback is on a grouped row.

Regards,
Gabi
