### ISSUE TITLE
elements.table.gridOptions (rowHeight)  not work in 2.5.1 but it work 2.2.2

### ISSUE THREAD

**Issue by juanetec** [Servoy/aggridcomponents#57]
Hi,
I had a process to increase the rowHeight of a Grid. 
It have been working until I have update to the 2.5.1 version.

`function increaseHeight(){
	elements.table.gridOptions={
			rowHeight: 150
		}
}`

Un Saludo 

Juan Ramírez

**Comment by gboros** [comment]
hi,
when is that method called? that should be before the grid is displayed

**Comment by juanetec** [comment]
Yes I know, you have explained to me. 
I did today the same process using the nggrid version 2.2.2 and then I update it to the latest one an I does not work.

**Comment by gboros** [comment]
I just did a quick test, calling that method on the form's onLoad, and it works fine, with v.2.5.1

**Comment by juanetec** [comment]
I don't know what I am doing wrong. 

I attach an example.
I am using servoy 2020.06.

[gridsWorkshop.zip](https://github.com/Servoy/aggridcomponents/files/5007324/gridsWorkshop.zip)

**Comment by gboros** [comment]
That is because of the 'breaking' change' in 2.5.0, check the release note: 'Component's property values that override the default now take precedence over the values set via NG-Grid Service or gridOptions|columnDef properties'. In your example, the grid has the rowHeight property set on the component, and that will be used; unset it (restore default) and then it will use the value set via gridOptions
