### ISSUE TITLE
Error After upgrading 2022-03-01

### ISSUE THREAD

**Issue by wvitpr** [Servoy/aggridcomponents#86]
Hi,
I have many related forms where I use formfoundset in datagrid with the aggrid option to show floating filters. eg. floatingFilter = true, Its worked really well for years and now its broken and I get the following error, this is a standard AGgrid option and is really handy for users to do a quick column search. The error below, could it be reverted or at least flag a warning so I can fix the code?  

ERROR com.servoy.j2db.util.Debug - Cannot addFoundSetFilterParam to related foundset

**Comment by paronne** [comment]
Hi, there has been a fix on 2022.3 for addFoundSetFilterParam(QBuilder) indeed. Was never fully supported on related foundset as the addFoundSetFilterParam(dataprovider, operator, value); since 2022.3.0 addFoundSetFilterParam is throwing an error if used on related foundset.
Have you tried already to use the updated version of the grid component ? Latest version of Grid Components for 2022.3.1 is the 2022.3.4; you should be able to upgrade the grid component via the Web Package Manager.

**Comment by wvitpr** [comment]
Hi,
I did try the latest version and I get a new error error.. data wont even display?? its strange,
ERROR org.sablo.websocket.WebsocketEndpoint - Error: illegal value 'FoundSet[Table:stk_stockcountlines,Size: 23,CachedRecords: 23,SELECTED INDEX: 0]' to set on the foundset property with foundsetSelector/datasource: , foundset is either pinned to form's foundset or to a related foundset myFoundset java.lang.RuntimeException: illegal value 'FoundSet[Table:stk_stockcountlines,Size: 23,CachedRecords: 23,SELECTED INDEX: 0]' to set on the foundset property with foundsetSelector/datasource: , foundset is either pinned to form's foundset or to a related foundset myFoundset

**Comment by gboros** [comment]
this issue is already fixed, but the fix is in both Servoy and NGGrids; an update will be released in the coming days

**Comment by gboros** [comment]
fixed by https://github.com/Servoy/aggridcomponents/commit/604327e6d8d91645a554f2530c7202a0da2db6c3

**Comment by gboros** [comment]
Servoy 2022.3.2 (LTS) & NG Grids 2022.3.5 are released with the fix for this issue
